export const GET_INTERVIEWS = 'GET_INTERVIEWS';
export const SET_INTERVIEWS = 'SET_INTERVIEWS';
export const UPDATE_INTERVIEWS = 'UPDATE_INTERVIEWS';
export const SET_UPDATE_INTERVIEWS = 'SET_UPDATE_INTERVIEWS';

export const GET_INTERVIEW = 'GET_INTERVIEW';
export const SET_INTERVIEW = 'SET_INTERVIEW';
export const ADD_INTERVIEW = 'ADD_INTERVIEW';
export const ADD_TO_INTERVIEWS = 'ADD_TO_INTERVIEWS';
export const UPDATE_INTERVIEW = 'UPDATE_INTERVIEW';

export const UPDATE_PAGE_LOAD = 'UPDATE_PAGE_LOAD';
export const SET_PAGE_LOAD = 'SET_PAGE_LOAD';

export const SET_USERS = 'SET_USERS';

export const SET_DIALERS = 'SET_DIALERS';
export const SET_QUEUES = 'SET_QUEUES';

export const SET_STATIC_DATA = 'SET_STATIC_DATA';

export const UPDATE_ANSWER_LINKS = 'UPDATE_ANSWER_LINKS';
export const UPDATE_QUESTION_LINKS = 'UPDATE_QUESTION_LINKS';

export const SET_ANSWER_LINKS = 'SET_ANSWER_LINKS';
export const SET_QUESTION_LINKS = 'SET_QUESTION_LINKS';
